import TopNavbar from '@/SharedComponents/TopNavbar';
import { ActiveUserProvider } from '@/contexts/ActiveUserContext';
import '@/styles/globals.css';
import Amplify from '@aws-amplify/core';
import { withAuthenticator } from '@aws-amplify/ui-react';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import config from '../aws-exports';

Amplify.configure(config);

export default function App({ Component, pageProps, router }: AppProps) {
  const { currentAuthenticatedUser } = pageProps;

  const AuthenticatedComponent =
    currentAuthenticatedUser || router.route === '/'
      ? Component
      : withAuthenticator(Component);

  return (
    <div>
      <Head>
        <title>HiRopes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ActiveUserProvider>
        <TopNavbar />
        <AuthenticatedComponent {...pageProps} />
      </ActiveUserProvider>
    </div>
  );
}
