import TopNavbar from '@/SharedComponents/TopNavbar';
import { ActiveUserProvider } from '@/contexts/ActiveUserContext';
import createEmotionCache from '@/styles/createEmotionCache';
import theme from '@/styles/theme';
import Amplify from '@aws-amplify/core';
import { withAuthenticator } from '@aws-amplify/ui-react';
import { CacheProvider } from '@emotion/react';
import { EmotionCache } from '@emotion/utils';
import { CssBaseline, ThemeProvider } from '@mui/material';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { useEffect } from 'react';
import config from '../aws-exports';

Amplify.configure(config);
const clientSideEmotionCache = createEmotionCache();

export interface NextWithMui extends AppProps {
  emotionCache?: EmotionCache;
}

export default function App({
  Component,
  pageProps,
  router,
  emotionCache = clientSideEmotionCache,
}: NextWithMui) {
  const { currentAuthenticatedUser } = pageProps;

  const AuthenticatedComponent =
    currentAuthenticatedUser || router.route === '/'
      ? Component
      : withAuthenticator(Component);

  useEffect(() => {
    // Remove the server-side injected CSS.
    const jssStyles = document.querySelector('#jss-server-side');
    if (jssStyles) {
      jssStyles?.parentElement?.removeChild(jssStyles);
    }
  }, []);

  return (
    <div>
      <Head>
        <title>HiRopes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CacheProvider value={emotionCache}>
        <ThemeProvider theme={theme}>
          <ActiveUserProvider>
            <CssBaseline />
            <TopNavbar />
            <AuthenticatedComponent {...pageProps} />
          </ActiveUserProvider>
        </ThemeProvider>
      </CacheProvider>
    </div>
  );
}
