import { ActiveUserProvider } from '@/contexts/ActiveUserContext';
import { CurrentActiveWorkoutProvider } from '@/contexts/CurrentActiveWorkoutContext';
import { GlobalSideNavProvider } from '@/contexts/GlobalSideNavContext';
import createEmotionCache from '@/styles/createEmotionCache';
import theme from '@/styles/theme';
import Amplify from '@aws-amplify/core';
import { CacheProvider } from '@emotion/react';
import { EmotionCache } from '@emotion/utils';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '@mui/material/styles';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { useEffect } from 'react';
import config from '../aws-exports';
import Layout from './Layout';

Amplify.configure({ ...config, ssr: true });
const clientSideEmotionCache = createEmotionCache();

export interface NextWithMui extends AppProps {
  emotionCache?: EmotionCache;
}

export const App = ({
  Component,
  pageProps,
  emotionCache = clientSideEmotionCache,
}: NextWithMui) => {
  useEffect(() => {
    // Remove the server-side injected CSS.
    const jssStyles = document.querySelector('#jss-server-side');
    if (jssStyles) {
      jssStyles?.parentElement?.removeChild(jssStyles);
    }
  }, []);

  return (
    <>
      <Head>
        <title>HiRopes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CacheProvider value={emotionCache}>
        <ThemeProvider theme={theme}>
          <ActiveUserProvider>
            <GlobalSideNavProvider>
              <CurrentActiveWorkoutProvider>
                <CssBaseline />
                <Layout>
                  <Component {...pageProps} />
                </Layout>
              </CurrentActiveWorkoutProvider>
            </GlobalSideNavProvider>
          </ActiveUserProvider>
        </ThemeProvider>
      </CacheProvider>
    </>
  );
};

export default App;
